In [2]:
import numpy as np
import pandas as pd
import random as rd
import math
import statistics as st

In [3]:
import numpy as np
data = [20,40,60,80]
arr = np.array(data)

print(arr)
print(type(arr))

[20 40 60 80]
<class 'numpy.ndarray'>


In [4]:
data = range(1,10)
print(data)
print(type(data))
print("---------------")
arr = np.array(data)
print(arr)
print(type(arr))

range(1, 10)
<class 'range'>
---------------
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [5]:
data = [20,40,60,80,100]
arr = np.array(data, np.integer)

print(arr.shape)
print(type(arr))
print(arr)

(5,)
<class 'numpy.ndarray'>
[ 20  40  60  80 100]


C:\Users\pepeb\AppData\Local\Temp\ipykernel_124380\2707183498.py:2: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
  arr = np.array(data, np.integer)


In [6]:
data = [20,40,60,80,100]
arr = np.array(data, np.floating)

print(arr.shape)
print(type(arr))
print(arr)

(5,)
<class 'numpy.ndarray'>
[ 20.  40.  60.  80. 100.]


C:\Users\pepeb\AppData\Local\Temp\ipykernel_124380\1620602494.py:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  arr = np.array(data, np.floating)


In [7]:
data = [20,40,60,80,100]
arr = np.array(data)

print(arr.dtype)
print(type(arr))
print(arr)

int64
<class 'numpy.ndarray'>
[ 20  40  60  80 100]


In [8]:
data = [3.14,12,15.1,22.4,30]
arr = np.array(data)

print(arr.dtype)
print(type(arr))
print(arr)

float64
<class 'numpy.ndarray'>
[ 3.14 12.   15.1  22.4  30.  ]


In [9]:
data = ['Python','C++','JavaScript']
arr = np.array(data)

print(arr.dtype)
print(type(arr))
print(arr)

<U10
<class 'numpy.ndarray'>
['Python' 'C++' 'JavaScript']


In [10]:
num = [20,30,40,50]
print(f'everage:{np.mean(num)}')
print(f'max:{np.max(num)}')
print(f'min:{np.min(num)}')

everage:35.0
max:50
min:20


In [13]:
import random as rd
rannum = np.random.rand(5)
print(rannum)
randind = rd.randint(0,10)
print(randind)
lange = rd.randrange(100,999)
print(lange)

[0.14438286 0.61319866 0.12324653 0.85207305 0.86538441]
10
481


In [ ]:
numlist = []
for i in range(3):
    numlist.append(rd.randint(1,101))

print(numlist)

[64, 45, 36]


In [ ]:
arr = np.array([[100,200,300],[20,30,40]],np.int64)

print(arr.shape)
print(type(arr))

(2, 3)
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([[100,200,300],[20,30,40]])

result = np.sum(arr)
print(f'sum:{result}')

sum:690


In [ ]:
#แกน y
arr = np.array([[100,200,300],[20,30,40]])

result = np.sum(arr, axis=0)
print(f'sum:{result}')

sum:[120 230 340]


In [ ]:
#แกน x
arr = np.array([[100,200,300],[20,30,40]])

result = np.sum(arr, axis=1)
print(f'sum:{result}')

sum:[600  90]


In [ ]:
arr = np.zeros(5)
print(f'info:{arr}')
print(f'info type:{type(arr)}')

info:[0. 0. 0. 0. 0.]
info type:<class 'numpy.ndarray'>


In [ ]:
arr = np.zeros((2,4))
print(f'info:{arr}')
print(f'info type:{type(arr)}')

info:[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
info type:<class 'numpy.ndarray'>


In [ ]:
arr = np.zeros((2,4), dtype=int)
print(f'info:{arr}')
print(f'info type:{arr.dtype}')

info:[[0 0 0 0]
 [0 0 0 0]]
info type:int64


In [ ]:
arr = np.zeros((2,3), dtype=[('x','int'),('y','float')])
print(f'info:{arr}')
print(f'info type:{arr.dtype}')

info:[[(0, 0.) (0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.) (0, 0.)]]
info type:[('x', '<i8'), ('y', '<f8')]


In [ ]:
arr = np.ones(5)
print(f'info:{arr}')
print(f'info type:{type(arr)}')

info:[1. 1. 1. 1. 1.]
info type:<class 'numpy.ndarray'>


In [ ]:
arr = np.ones((2,4), dtype=int)
print(f'info:{arr}')
print(f'info type:{arr.dtype}')

info:[[1 1 1 1]
 [1 1 1 1]]
info type:int64


In [ ]:
arr = np.ones((2,3), dtype=[('x','int'),('y','float')])
print(f'info:{arr}')
print(f'info type:{arr.dtype}')

info:[[(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]]
info type:[('x', '<i8'), ('y', '<f8')]


In [ ]:
arr = np.array([100,200,300,400])
print(arr[2:])

[300 400]


In [ ]:
arr = np.array([100,200,300,400])
print(arr[:2])

[100 200]


In [ ]:
arr = np.array([100,200,300,400])
print(arr[1:3])

[200 300]


In [ ]:
arr = np.array([[100,200,300,400],[10,20,30,40]])
print(f'r1 column1 : {arr[0,0]}')
print(f'r2 column1 : {arr[1,0]}')

r1 column1 : 100
r2 column1 : 10


In [ ]:
arr = np.array([[100,200,300,400],[10,20,30,40]])
print(f'r1 column2 : {arr[0,1]}')
print(f'r2 column2 : {arr[1,1]}')

r1 column2 : 200
r2 column2 : 20


In [ ]:
arr = np.array([[10,20,30],
               [100,200,300],
               [1000,2000,3000],
               [10000,20000,30000]])

arr[0:,0:]

array([[   10,    20,    30],
       [  100,   200,   300],
       [ 1000,  2000,  3000],
       [10000, 20000, 30000]])

In [ ]:
arr = np.array([100,200,300,400])

result = arr[arr >= 300]
result

array([300, 400])

In [ ]:
arr = np.array([100,200,300,400])

result = arr[arr >= 1000]
result

array([], dtype=int64)

In [ ]:
arr = np.array([100,200,300,400])

result = np.where(arr <= 200,arr,0)
result

array([100, 200,   0,   0])

In [ ]:
arr = np.array([100,200,300,400])

result = np.where(arr >= 1000,arr,0)
result

array([0, 0, 0, 0])

In [ ]:
arr1 = np.array([[100,200],[300,400]])
arr2 = np.array([[1000,2000],[3000,4000]])

arr = np.append(arr1,arr2)
arr

array([ 100,  200,  300,  400, 1000, 2000, 3000, 4000])

In [ ]:
arr1 = np.array([[100,200],[300,400]])
arr2 = np.array([[1000,2000],[3000,4000]])

arr = np.append(arr1,arr2,axis=0)
arr

array([[ 100,  200],
       [ 300,  400],
       [1000, 2000],
       [3000, 4000]])

In [ ]:
arr1 = np.array([[100,200],[300,400]])
arr2 = np.array([[1000,2000],[3000,4000]])

arr = np.append(arr1,arr2,axis=1)
arr

array([[ 100,  200, 1000, 2000],
       [ 300,  400, 3000, 4000]])

In [ ]:
arr = np.array([[101,202,303],
               [100,200,300],
               [110,220,330],
               [111,222,333]])

print(pd.DataFrame(arr))

     0    1    2
0  101  202  303
1  100  200  300
2  110  220  330
3  111  222  333


In [ ]:
data = {'name': ['James','Katie','Marcus'],
        'city': ['New York','Bangkok','Paris']}
df = pd.DataFrame(data)
result = df.drop(columns='city')
result
#df

name
0   James
1   Katie
2  Marcus

In [ ]:
data = {'name': ['James','Katie','Marcus'],
        'city': ['New York','Bangkok','Paris'],
        'code': [10500,30045,48057]}

df = pd.DataFrame(data)
result = df.drop(columns=['city','code'])
result

name
0   James
1   Katie
2  Marcus

In [ ]:
data = {'name': ['James','Katie','Marcus'],
        'city': ['New York','Bangkok','Paris'],
        'code': [10500,30045,48057]}

df = pd.DataFrame(data)
result = df.drop(index=[2,2])
result

name      city   code
0  James  New York  10500
1  Katie   Bangkok  30045

In [ ]:
datas = {
    'a':[1,2,2,3,4,2,1,4,4,3,5,1,2]
    }

df = pd.DataFrame(datas)
#result = df.drop_duplicates()
result = df.drop_duplicates(keep='last')
result

a
8   4
9   3
10  5
11  1
12  2

In [ ]:
data = [
    ['Max',185,27000],['Reece',190,90675],['Joe',174,23456],['Lee',185,75000]
]

colname = ['name','height','salary']
df1 = pd.DataFrame(data, columns=colname)
df2 = df1.rename(columns={
    'name':'ชื่อ',
    'height':'ส่วนสูง'
    ,'salary':'รายได้'})

df1
df2

ชื่อ  ส่วนสูง  รายได้
0    Max      185   27000
1  Reece      190   90675
2    Joe      174   23456
3    Lee      185   75000

In [ ]:
arr = np.array([[98, 63, 58],
                [82, 10, 93],
                [92, 14, 99]])
df = pd.DataFrame(arr)

def ass(x):
    return x+5

result = df.apply(ass)
result

0   1    2
0  103  68   63
1   87  15   98
2   97  19  104

In [ ]:
arr = np.array([[98, 63, 58],[82, 10, 93],[92, 14, 99]])
df = pd.DataFrame(arr)

result = df.apply(lambda x:x + 1)
result

0   1    2
0  99  64   59
1  83  11   94
2  93  15  100

In [ ]:
df = pd.DataFrame(
    {
        'A':[31, 11],
        'B':[94, 90]
    }
)

print(f'-----Gan X-----')
result1 = df.apply(np.sum,axis=0)
print(result1)
print(f'-----Gan Y-----')
result2 = df.apply(np.sum,axis=1)
print(result2)

-----Gan X-----
A     42
B    184
dtype: int64
-----Gan Y-----
0    125
1    101
dtype: int64


In [ ]:
df = pd.DataFrame(
    {
        'A':[25, 81],
        'B':[36, 441]
    }
)

results = df.applymap(math.sqrt)
results

C:\Users\pepeb\AppData\Local\Temp\ipykernel_122276\3217121449.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  results = df.applymap(math.sqrt)


A     B
0  5.0   6.0
1  9.0  21.0

In [ ]:
info = [10, 83, 24, 90]
ps = pd.Series(info)

print(ps)
print(type(ps))

0    10
1    83
2    24
3    90
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
data = [72, 46, 59, 23]
ndata = np.array(data)
ps = pd.Series(ndata)

print('----------')
print(ps)


----------
0    72
1    46
2    59
3    23
dtype: int64


In [ ]:
person = ['จารุวรรณ', 'สุชาติ', 'สายใจ', 'ประทีป']
height = [176, 188, 181, 180]

ps = pd.Series(height, index=person)

ps

จารุวรรณ    176
สุชาติ      188
สายใจ       181
ประทีป      180
dtype: int64

In [ ]:
dic = {'Anthony':155, 'วินัย':200, 'Emma':177, 'Zoey':170}
ps = pd.Series(dic)

ps

Anthony    155
วินัย      200
Emma       177
Zoey       170
dtype: int64

In [ ]:
dic = {'Anthony':155, 'วินัย':200, 'Emma':177, 'Zoey':170}
ps = pd.Series(dic)

print(ps[0])
print(ps[-2])
print(ps[3])
print(ps['Anthony'])
print(ps['วินัย'])

155
177
170
155
200


C:\Users\pepeb\AppData\Local\Temp\ipykernel_122276\3689025132.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ps[0])
C:\Users\pepeb\AppData\Local\Temp\ipykernel_122276\3689025132.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ps[-2])
C:\Users\pepeb\AppData\Local\Temp\ipykernel_122276\3689025132.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ps[3])


In [ ]:
data = [474, 366, 825, 166, 487, 713, 505]
ps = pd.Series(data)

print(ps[:])
print(ps[1:4])
print(ps[2:])
print(ps[:4])

0    474
1    366
2    825
3    166
4    487
5    713
6    505
dtype: int64
1    366
2    825
3    166
dtype: int64
2    825
3    166
4    487
5    713
6    505
dtype: int64
0    474
1    366
2    825
3    166
dtype: int64


In [ ]:
data = [18, 42, 98, 61, 35, 37]
df = pd.DataFrame(data)

print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


0
0  18
1  42
2  98
3  61
4  35
5  37

In [ ]:
colsname = ['income']
data = [2, 50, 47, 82, 32, 12]
df = pd.DataFrame(data, columns=colsname)

df

income
0       2
1      50
2      47
3      82
4      32
5      12

In [ ]:
human = ['วิเชียร', 'วีระ', 'ชุติมา', 'ประเสริฐ']
height = [186, 196, 174, 167]

data = list(zip(human, height))

colsname = ['ชื่อ','ส่วนสูง']
df = pd.DataFrame(data, columns=colsname)

df

ชื่อ  ส่วนสูง
0   วิเชียร      186
1      วีระ      196
2    ชุติมา      174
3  ประเสริฐ      167

In [ ]:
data = [
    ['Max',185,27000],
    ['Reece',190,90675],
    ['Joe',174,23456],
    ['Lee',185,75000]
]

colsname = ['ชื่อ','ส่วนสูง','เงินเดือน']
df = pd.DataFrame(data, columns=colsname)

df

ชื่อ  ส่วนสูง  เงินเดือน
0    Max      185      27000
1  Reece      190      90675
2    Joe      174      23456
3    Lee      185      75000

In [ ]:
data = [
    ['Max',185,27000],
    ['Reece',190,90675],
    ['Joe',174,23456],
    ['Lee',185,75000]
]

colsname = ['name','height','salary']
df = pd.DataFrame(data, columns=colsname, index=['A','B','C','D'])

df
#df['height']['A']
#df['name']['C']

name  height  salary
A    Max     185   27000
B  Reece     190   90675
C    Joe     174   23456
D    Lee     185   75000

In [ ]:
data = [
    ['Max',185,27000],
    ['Reece',190,90675],
    ['Joe',174,23456],
    ['Lee',185,75000]
]

colsname = ['name','height','salary']
df = pd.DataFrame(data, columns=colsname)

print(df)
print(df.shape)

    name  height  salary
0    Max     185   27000
1  Reece     190   90675
2    Joe     174   23456
3    Lee     185   75000
(4, 3)


In [ ]:
data = [
    {'ชื่อ':'อนันต์','ส่วนสูง':178,'เงินเดือน':50000},
    {'ชื่อ':'ไพโรจน์','ส่วนสูง':153,'เงินเดือน':55000},
    {'ชื่อ':'มัณฑนา','ส่วนสูง':160,'เงินเดือน':70000},
    {'ชื่อ':'พิเชษฐ์','ส่วนสูง':188,'เงินเดือน':90000}
]

df = pd.DataFrame(data, index=['a','b','c','d'])

df

ชื่อ  ส่วนสูง  เงินเดือน
a   อนันต์      178      50000
b  ไพโรจน์      153      55000
c   มัณฑนา      160      70000
d  พิเชษฐ์      188      90000

In [ ]:
person = ['พรชัย', 'นุจรี', 'นฤมล', 'พิมพ์ใจ']
height = [196, 159, 176, 200]
age = [24, 27, 81, 39]

data = {

    'ชื่อ' : person,
    'ส่วนสูง' : height,
    'อายุ' : age
}

df = pd.DataFrame(data)
df

ชื่อ  ส่วนสูง  อายุ
0    พรชัย      196    24
1    นุจรี      159    27
2     นฤมล      176    81
3  พิมพ์ใจ      200    39

In [ ]:
import pandas as pd

data1 = [
    ['Max',185,27000],
    ['Reece',190,90675],
    ['Joe',174,23456],
    ['Lee',185,75000]
]

data2 = [
    ['James',187,47850],
    ['Leonardo',173,76000]
]

colname = ['name','height','salary']
df1 = pd.DataFrame(data1, columns=colname)
df2 = pd.DataFrame(data2, columns=colname)

df = pd.concat([df1,df2], ignore_index=True)
df

name  height  salary
0       Max     185   27000
1     Reece     190   90675
2       Joe     174   23456
3       Lee     185   75000
4     James     187   47850
5  Leonardo     173   76000

In [ ]:
data1 = [
    ['Max',185,27000],
    ['Reece',190,90675],
    ['Joe',174,23456],
    ['Lee',185,75000]
]

data2 = [
    ['James',187,47850,'LA'],
    ['Leonardo',173,76000,'SF']
]

colname1 = ['name','height','salary']
colname2 = ['name','height','salary','city']
df1 = pd.DataFrame(data1, columns=colname1)
df2 = pd.DataFrame(data2, columns=colname2)

df = pd.concat([df1,df2],sort=False,ignore_index=True)
df

name  height  salary city
0       Max     185   27000  NaN
1     Reece     190   90675  NaN
2       Joe     174   23456  NaN
3       Lee     185   75000  NaN
4     James     187   47850   LA
5  Leonardo     173   76000   SF

In [ ]:
data = [
    ['Max',185,27000],
    ['Reece',190,90675],
    ['Joe',174,23456],
    ['Lee',185,75000]
]

colsname = ['name','height','salary']
df = pd.DataFrame(data, columns=colsname)

result = df.loc[0]
result1 = df.loc[[0,3]]
result2 = df.loc[0,'name']
result3 = df.loc[0:2]
result4 = df.loc[0:2, 'name']
result5 = df.loc[[True,True,False,False]]
result6 = df.loc[df['salary'] >= 30000]

result6

name  height  salary
1  Reece     190   90675
3    Lee     185   75000

In [ ]:
data = [
    ['Max', 185, 27000, 'Male'],
    ['Anna', 165, 31000, 'Female'],
    ['Joe', 174, 23456, 'Male'],
    ['Lily', 160, 29000, 'Female'],
    ['Ben', 180, 45000, 'Male'],
    ['Sara', 170, 34000, 'Female'],
    ['Tom', 182, 50000, 'Male'],
    ['Nina', 168, 36000, 'Female']]

colname = ['name','height','salary','gender']
df = pd.DataFrame(data, columns=colname)

df_group = df.groupby(['gender'])[['gender']].count()
df_group1 = df.groupby(['gender'])[['salary']].sum()

df_group1

salary
gender        
Female  130000
Male    145456

In [ ]:
data = {
    'ID':[100,101,102,103],
    'Name':['วิเชียร', 'ชาญชัย', 'จักรพงษ์', 'มัณฑนา'],
    'Salary':[20000,22000,np.nan,pd.NaT],
    'Age':[35,36,np.nan,None]
}

df = pd.DataFrame(data)
#df_correct = df.dropna()
#df_correct = df.dropna(inplace=True)
#df_correct = df.dropna(thresh=2)
df_correct = df.dropna(axis=0)

df_correct

ID     Name Salary   Age
0  100  วิเชียร  20000  35.0
1  101   ชาญชัย  22000  36.0

In [ ]:
data = {
    'ID':[100,101,102,103],
    'Name':['วิเชียร', 'ชาญชัย', 'จักรพงษ์', 'มัณฑนา'],
    'Salary':[20000,22000,np.nan,pd.NaT],
    'Age':[35,pd.NaT,np.nan,None]
}

df = pd.DataFrame(data)
result = df.isna().sum()
result = df.isna().mean()

result

ID        0.00
Name      0.00
Salary    0.50
Age       0.75
dtype: float64

In [ ]:
data = {
    'ID':[100,101,102,103],
    'Name':['วิเชียร', 'ชาญชัย', 'จักรพงษ์', 'มัณฑนา'],
    'Salary':[20000,22000,np.nan,pd.NaT],
    'Age':[35,pd.NaT,np.nan,None]
}

df = pd.DataFrame(data)
df.isnull()

ID   Name  Salary    Age
0  False  False   False  False
1  False  False   False   True
2  False  False    True   True
3  False  False    True   True

In [ ]:
data = {
    'ID':[100,101,102,103],
    'Name':['วิเชียร', 'ชาญชัย', 'จักรพงษ์', 'มัณฑนา'],
    'Salary':[20000,22000,np.nan,19000],
    'Age':[35,36,np.nan,37]
}

df = pd.DataFrame(data)
result = df.interpolate()

result

C:\Users\pepeb\AppData\Local\Temp\ipykernel_122276\3933014241.py:9: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  result = df.interpolate()


ID      Name   Salary   Age
0  100   วิเชียร  20000.0  35.0
1  101    ชาญชัย  22000.0  36.0
2  102  จักรพงษ์  20500.0  36.5
3  103    มัณฑนา  19000.0  37.0

In [ ]:
data = {
    'ID':[100,101,102,103],
    'Name':['วิเชียร', 'ชาญชัย', 'จักรพงษ์', 'มัณฑนา'],
    'Salary':[20000,22000,np.nan,pd.NaT],
    'Age':[35,36,np.nan,None]
}

df = pd.DataFrame(data)
df_correct = df.fillna({'Salary':30000,'Age':23})

df_correct

C:\Users\pepeb\AppData\Local\Temp\ipykernel_122276\1390253118.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_correct = df.fillna({'Salary':30000,'Age':23})


ID      Name  Salary   Age
0  100   วิเชียร   20000  35.0
1  101    ชาญชัย   22000  36.0
2  102  จักรพงษ์   30000  23.0
3  103    มัณฑนา   30000  23.0

In [ ]:
data = {
    'ID':[100,101,102,103],
    'Name':['วิเชียร', 'ชาญชัย', 'จักรพงษ์', 'มัณฑนา'],
    'Salary':[20000,22000,np.nan,pd.NaT],
    'Age':[35,36,np.nan,None]
}

df = pd.DataFrame(data)
df_correct = df.fillna(method='ffill')

df_correct

C:\Users\pepeb\AppData\Local\Temp\ipykernel_122276\2822492853.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_correct = df.fillna(method='ffill')
C:\Users\pepeb\AppData\Local\Temp\ipykernel_122276\2822492853.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_correct = df.fillna(method='ffill')


ID      Name  Salary   Age
0  100   วิเชียร   20000  35.0
1  101    ชาญชัย   22000  36.0
2  102  จักรพงษ์   22000  36.0
3  103    มัณฑนา   22000  36.0

In [ ]:
data = [84, 112, 137, np.nan]
arr = np.array(data)

normalmean = np.mean(arr)
cleanmean = np.nanmean(arr)

print(f'Mean:{normalmean}')
print(f'Cleanmean: {cleanmean}')

Mean:nan
Cleanmean: 111.0


In [ ]:
data = [84, 112, 137, 165]

np.mean(data)

np.float64(124.5)

In [ ]:
data = [
    ['John',180,16000],
    ['Jane',165,18500],
    ['Justin',190,27500],
    ['Jammies',172,37500]
]

colname = ['name','height','salary']
df = pd.DataFrame(data, columns=colname)

df['height'].mean()
print(df['salary'].mean())

24875.0


In [ ]:
data = [
    ['Max', 185, 27000, 'Male'],
    ['Anna', 165, 31000, 'Female'],
    ['Joe', 174, 23456, 'Male'],
    ['Lily', 160, 29000, 'Female'],
    ['Ben', 180, 45000, 'Male'],
    ['Sara', 170, 34000, 'Female'],
    ['Tom', 182, 50000, 'Male'],
    ['Nina', 168, 36000, 'Female']]

colname = ['Name','Height','Salary','Gender']
df = pd.DataFrame(data, columns=colname)

role = df.groupby(['Gender'])
df_groupby_role = role[['Gender','Salary']]
result = df_groupby_role.mean(['Height','Salary'])

result

Salary
Gender         
Female  32500.0
Male    36364.0

In [ ]:
data = [197, 197, 107.5, 183, 67, 127, 117]
rs = st.fmean(data)

print(f'{rs:3f}')

142.214286


In [ ]:
data = [3,5,7]
result = st.geometric_mean(data)

print(f'{result:3f}')

4.717694


In [ ]:
#rs = np.average([200,300,900], weights=3)
#rs

In [ ]:
df = pd.DataFrame(
    {
    'x':[1,2,3],
    'y':[1,1,1]
    }
)

rs = np.average(df['x'], weights=df['y'])
resalt = sum(df['x'] * df['y']) / sum(df['y'])

rs
resalt

2.0

In [ ]:
data = [74, 133.05, 130, 185.75, 179, 129.78, 84]
result = st.harmonic_mean(data)

f'Speed:{result:.3f}'

'Speed:118.040'

In [ ]:
data = [181, 61, 196, 166, 78,196]
rds = np.median(data)

f'MD: {rds:.3f}'

'MD: 173.500'

In [ ]:
data = [181, 61, 196, 166, 78,196]
rs = st.median(data)
rsh = st.median_low(data)
rsl = st.median_high(data)

print(f'median:{rs}')
print(f'median_low:{rsh}')
print(f'median_high:{rsl}')

median:173.5
median_low:166
median_high:181


In [ ]:
#Random num
numlist = []
for i in range(6):
    numlist.append(rd.randrange(-5,5))

numlist

[3, 0, 0, 3, -4, 2]

In [ ]:
import random
names = [
    "สมชาย", "สมหญิง", "วิชัย", "นฤมล", "สุชาติ", "ณัฐธิดา", "ประเสริฐ", "ปวีณา", "อาคม", "ชุติมา",
    "เกรียงศักดิ์", "ศิริพร", "วรากร", "มัณฑนา", "ศักดา", "พิมพ์ใจ", "อนันต์", "อรอนงค์", "จักรพงษ์", "อัจฉรา",
    "วิเชียร", "วรรณา", "ณรงค์", "กรรณิการ์", "บุญเลิศ", "สายใจ", "พรชัย", "นงนุช", "สมบูรณ์", "สุนิสา",
    "วีระ", "จินตนา", "ศุภชัย", "สุกัญญา", "พิเชษฐ์", "อรทัย", "ชาญชัย", "ธิดารัตน์", "ไพโรจน์", "จารุวรรณ",
    "ธีระ", "กัลยา", "วินัย", "เบญจวรรณ", "ประทีป", "มยุรี", "กิตติ", "นุจรี", "ถาวร", "สุกัญญา",
]


namelist = []

for i in range(5):
    selected = random.choice(names)
    namelist.append(selected)

namelist

['สมบูรณ์', 'อาคม', 'ปวีณา', 'พรชัย', 'ณรงค์']

In [ ]:
name = ["James", "Emily", "Michael", "Olivia", "William", "Sophia", "David", "Emma", "John", "Ava",
    "Daniel", "Mia", "Matthew", "Isabella", "Joseph", "Charlotte", "Andrew", "Amelia", "Christopher", "Harper",
    "Joshua", "Evelyn", "Anthony", "Abigail", "Nicholas", "Ella", "Jonathan", "Grace", "Samuel", "Chloe",
    "Benjamin", "Lily", "Alexander", "Zoey", "Ryan", "Sofia", "Jacob", "Aria", "Ethan", "Scarlett",
    "Nathan", "Layla", "Logan", "Avery", "Justin", "Ellie", "Kevin", "Nora", "Brian", "Hannah"]

nlist = []

for i in range(4):
    selected = random.choice(name)
    nlist.append(selected)

nlist

['Kevin', 'Scarlett', 'Joseph', 'Abigail']